In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.5 MB 1.7 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/12.5 MB 2.1 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.5 MB 2.5 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.5 MB 2.9 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.5 MB 3.0 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.5 MB 3.1 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.5 MB 3.2 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.5 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.5 MB 3.6 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.5 MB 3.7 MB/s eta 0:00:02
   -----------------


[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

print(np.__version__)

2.5.2


1. Creating arrays

In [3]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [ ]:
arr_list1 = np.array(list1) # Creating array using list
print(arr_list1)

[1 2 3]


In [ ]:
print(type(arr_list1)) # check data type of variable

<class 'numpy.ndarray'>


In [ ]:
print(arr_list1.ndim) # check dimension of array

1


In [7]:
# Creating 2D array using 2 lists
list1 = [1,2,3]
list2 = [4,5,6]
arr_list2 = np.array([list1,list2])
print(arr_list2)

[[1 2 3]
 [4 5 6]]


In [8]:
print(arr_list2.ndim)

2


In [9]:
# Creating 3D array using 3 lists
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list3 = np.array([[list1,list2,list3]])
print(arr_list3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [10]:
print(arr_list3.ndim)

3


2. numpy array attributes

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [5]:
# Attributes of Array (properties of array)
print("Shape", arr1.shape) # shape = rows X columns
print("Size", arr1.size) # number of elements in array
print("Data type", arr1.dtype) # data type of array
print("Dimension", arr1.ndim) # dimension of array

Shape (2, 3)
Size 6
Data type int64
Dimension 2


In [7]:
# 3D array
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr2 = np.array([[list1,list2,list3]])

print("Shape", arr2.shape) # shape = rows X columns
print("Size", arr2.size) # number of elements in array
print("Data type", arr2.dtype) # data type of array
print("Dimension", arr2.ndim) # dimension of array

Shape (1, 3, 3)
Size 9
Data type int64
Dimension 3


3. Array initialization methods

In [8]:
# zeros array : all elements are 0
arr_zeros = np.zeros((2,3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# ones array : all elements are 1
arr_ones = np.ones((2,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# full array : all elements are same based on given value
arr_full = np.full((2,3),5)
print(arr_full)

[[5 5 5]
 [5 5 5]]


In [11]:
# Identity matrix : diagonal elements are 1
arr_identity = np.eye(3)
print(arr_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# empty array
print(np.empty(2))

[0. 0.]


In [18]:
# evenly spaced array
arr_evenly_spaced = np.arange(2,10,2)
print(arr_evenly_spaced)

[2 4 6 8]


In [20]:
# specific number of equally spaced values between start and end
arr_linspace = np.linspace(2,100,5)
print(arr_linspace)

[  2.   26.5  51.   75.5 100. ]


In [21]:
# random values array - float
arr_random = np.random.random((2,3))
print(arr_random)

[[0.82869584 0.71943783 0.64069671]
 [0.64261044 0.85104361 0.22656899]]


In [23]:
# random values array - integer
arr_random = np.random.randint(2,10,(2,3))
print(arr_random)

[[5 2 9]
 [5 3 5]]


4. Array Indexing and Slicing

In [3]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [4]:
print(a[0]) # first element
print(a[4]) # last element

1
9


In [5]:
print(a[-1]) # last element

9


In [6]:
# slicing 
# array[start:end:step]
print(a[0:4:2]) # [start:end:step]
print(a[::2]) # [start:end:step]
print(a[::-1]) # reverse array

[1 5]
[1 5 9]
[9 7 5 3 1]


In [7]:
# Indexing on 2D array
a = np.array([[1,3,5],[7,9,11]])
print(a)


[[ 1  3  5]
 [ 7  9 11]]


In [9]:
print(a[0]) # first row
print(a[1]) # second row
print(a[0][0]) # first element of first row
print(a[1][2]) # third element of second row

[1 3 5]
[ 7  9 11]
1
11


In [10]:
print(a[:,0]) # first column
print(a[:,1]) # second column
print(a[:,2]) # third column


[1 7]
[3 9]
[ 5 11]


In [13]:
# 3D Array: [height, rows,column]
a = np.array([[1,3,5],[7,9,11],[13,15,17]])
print(a)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [16]:
print(a[0])
print(a[:,0]) # first column
print(a[:,1]) # second column
print(a[:,2]) # third column

[1 3 5]
[ 1  7 13]
[ 3  9 15]
[ 5 11 17]
