In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.5 MB 1.7 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/12.5 MB 2.1 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.5 MB 2.5 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.5 MB 2.9 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.5 MB 3.0 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.5 MB 3.1 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.5 MB 3.2 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.5 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.5 MB 3.6 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.5 MB 3.7 MB/s eta 0:00:02
   -----------------


[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

print(np.__version__)

2.5.2


1. Creating arrays

In [3]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [ ]:
arr_list1 = np.array(list1) # Creating array using list
print(arr_list1)

[1 2 3]


In [ ]:
print(type(arr_list1)) # check data type of variable

<class 'numpy.ndarray'>


In [ ]:
print(arr_list1.ndim) # check dimension of array

1


In [7]:
# Creating 2D array using 2 lists
list1 = [1,2,3]
list2 = [4,5,6]
arr_list2 = np.array([list1,list2])
print(arr_list2)

[[1 2 3]
 [4 5 6]]


In [8]:
print(arr_list2.ndim)

2


In [9]:
# Creating 3D array using 3 lists
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list3 = np.array([[list1,list2,list3]])
print(arr_list3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [10]:
print(arr_list3.ndim)

3
